<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgbLuDx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgbLuDx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQgbLuDx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQgbLuDx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQgbLuDx\App_KernelProdContainer([
    'container.build_hash' => 'QgbLuDx',
    'container.build_id' => 'e87961d4',
    'container.build_time' => 1654589014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgbLuDx');
