<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9K89FW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9K89FW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9K89FW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9K89FW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9K89FW\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9K89FW',
    'container.build_id' => '157b9bfa',
    'container.build_time' => 1654589287,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9K89FW');
